apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.7.17
    helm:
      values: |
        controller:
          image:
            registry: docker.io
            repository: jenkins/jenkins
            tag: "2.504.1-jdk17"
          serviceType: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            hostName: jenkins.local
          admin:
            username: admin
          installPlugins:
            - kubernetes
            - workflow-aggregator
            - git
            - credentials
            - plain-credentials
            - credentials-binding
            - docker-workflow
          javaOpts: "-Djenkins.install.runSetupWizard=false"
        persistence:
          enabled: false



  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
