apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.34.0    
    helm:
      values: |
        global:
          enabled: true

        injector:
          enabled: false

        server:
          securityContext:
            runAsUser: 100
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          extraInitContainers:
            - name: fix-permissions
              image: busybox:1.36
              command:
                - sh
                - -c
                - |
                  chown -R 100:1000 /vault/data
                  chmod 750 /vault/data
              securityContext:
                runAsUser: 0
                runAsGroup: 0
                runAsNonRoot: false
              volumeMounts:
                - name: data
                  mountPath: /vault/data

          dev:
            enabled: false

          ha:
            enabled: true
            replicas: 1

            raft:
              enabled: true
              setNodeId: true

          dataStorage:
            enabled: true
            size: 2Gi
            mountPath: "/vault/data"
            accessMode: ReadWriteOnce

        ui:
          enabled: true
          serviceType: ClusterIP
          
      
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
