apiVersion: v1
kind: Secret
metadata:
  name: {{ include "petclinic.fullname" . }}-db
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_URL: {{ .Values.postgres.url | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASS: {{ .Values.postgres.password | quote }}
