prometheus:
  prometheusSpec:
    retention: 1d
    scrapeInterval: 30s
    evaluationInterval: 30s

    storageSpec: {}

grafana:
  enabled: true

  persistence:
    enabled: false

  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
  
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: browser

alertmanager:
  enabled: true
  
  alertmanagerSpec:
    storage: {}

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

defaultRules:
  create: true