prometheus:
  prometheusSpec:
    retention: 1d
    scrapeInterval: 30s
    evaluationInterval: 30s

    storageSpec: {}

grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  persistence:
    enabled: false

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - grafana.local

    path: /
    pathType: Prefix

  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

  additionalDataSources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
      isDefault: true
  
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: browser

alertmanager:
  enabled: true
  
  alertmanagerSpec:
    storage: {}

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

defaultRules:
  create: true